<template>
  <v-app>
    <v-navigation-drawer app clipped>
      <v-list-item>
        <v-list-item-content>
          <v-list-item-title class="title">Application</v-list-item-title>
          <v-list-item-subtitle>subtext</v-list-item-subtitle>
        </v-list-item-content>
      </v-list-item>

      <v-divider></v-divider>

      <v-list shaped>
        <v-list-item
          v-for="(item, index) in ['nav item 1', 'nav item 2', 'nav item 3']"
          :key="index"
          link
        >
          <v-list-item-icon>
            <v-icon>fa-home</v-icon>
          </v-list-item-icon>

          <v-list-item-content>
            <v-list-item-title>{{ item }}</v-list-item-title>
          </v-list-item-content>
        </v-list-item>
      </v-list>
    </v-navigation-drawer>

    <v-app-bar app clipped-left>
      <v-toolbar-title class="headline text-uppercase">
        <a href="https://e-go-digital.com/" target="_blank">
          <img :src="require('./assets/ego-logo.svg')" id="ego-logo" />
        </a>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn text href="https://github.com/egodigital/generator-ego" target="_blank">
        <span class="mr-2">
          Generated by
          <strong>generator-ego</strong>
        </span>
        <v-icon>fas fa-external-link-alt</v-icon>
      </v-btn>
    </v-app-bar>

    <v-content>
      <router-view />
    </v-content>
  </v-app>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "App",
  data: () => ({
    //
  })
});
</script>

<style lang="sass">
#ego-logo 
  height: 32px
  margin-top: 12px


a 
  text-decoration: none

</style>