<template>
  <v-app>
    <v-toolbar app height="64px">
      <v-toolbar-title class="headline text-uppercase">
        <a target="_blank" href="https://e-go-digital.com">
          <img id="ego-logo" class="mt-2" src="./assets/ego_digital_lg_md_sm.svg">
        </a>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn
        flat
        href="https://github.com/egodigital/generator-ego"
        target="_blank"
        class="mt-2"
      >
        <span class="mr-2">Generated by <strong>generator-ego</strong></span>
        <v-icon>open_in_new</v-icon>
      </v-btn>
    </v-toolbar>

    <v-content>
      <HelloWorld/>
    </v-content>
  </v-app>
</template>

<script>

import HelloWorld from './components/HelloWorld';

export default {
  name: 'App',
  components: {
    HelloWorld,
  },
  data() {
    return {
      //
    };
  },
};

</script>

<style>

#ego-logo {
  height: 32px;
}

</style>
