/**
 * Generated by 'generator-ego' (https://github.com/egodigital/generator-ego)
 *
 * by e.GO Digital GmbH, Aachen, Germany (https://e-go-digital.com)
 */

import * as egoose from '@egodigital/egoose';

(async () => {

    const RESPONSE = await egoose.GET('https://randomuser.me/api?nat=de&results=20');
    if (200 !== RESPONSE.code) {
        throw new Error(`Unexpected response: [${ RESPONSE.code }] '${ RESPONSE.status }'`);
    }

    console.log(
        await RESPONSE.readJSON()
    );

})();