<template>
  <v-app>
    <v-toolbar app>
      <v-toolbar-title class="headline text-uppercase">
        <a href="https://e-go-digital.com/" target="_blank">
          <img :src="require('./assets/logo.svg')"
               id="ego-logo" />
        </a>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn
        flat
        href="https://github.com/egodigital/generator-ego"
        target="_blank"
      >
        <span class="mr-2">Generated by <strong>generator-ego</strong></span>
        <v-icon>open_in_new</v-icon>
      </v-btn>
    </v-toolbar>

    <v-content>
      <router-view/>
    </v-content>
  </v-app>
</template>

<script>

export default {
  name: 'App',
  data () {
    return {
      //
    }
  }
}
</script>

<style>

#ego-logo {
  height: 32px;
  margin-top: 12px;
}

a {
  text-decoration: none;
}

</style>

