/**
 * Generated by 'generator-ego' (https://github.com/egodigital/generator-ego)
 *
 * by e.GO Digital GmbH, Aachen, Germany (https://github.com/egodigital)
 */

import * as express from 'express';

/**
 * An API context.
 */
export interface ApiContext {
    /**
     * Stores the current host instance.
     */
    readonly host: express.Express;
}
